create sequence pk_dependente
CREATE TABLE FUNCIONARIO (
    NOME     VARCHAR(60) NOT NULL,
    CPF      VARCHAR(11) NOT NULL,
    SALARIO  NUMERIC(15,2)
);

CREATE TABLE DEPENDENTE (
    ID               INTEGER NOT NULL,
    NOME             VARCHAR(60) NOT NULL,
    CALCULAIR        CHAR(1) NOT NULL,
    CALCULAINSS      CHAR(1) NOT NULL,
    FUNCIONARIO_CPF  VARCHAR(11) NOT NULL
);

ALTER TABLE FUNCIONARIO ADD CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (CPF);
ALTER TABLE DEPENDENTE ADD CONSTRAINT PK_DEPENDENTE PRIMARY KEY (ID);
ALTER TABLE DEPENDENTE ADD CONSTRAINT FK_DEPENDENTE_1 FOREIGN KEY (FUNCIONARIO_CPF) REFERENCES FUNCIONARIO (CPF) ON DELETE CASCADE ON UPDATE CASCADE;

COMMENT ON TABLE FUNCIONARIO IS 'Cadastro de Funcionário';
COMMENT ON TABLE DEPENDENTE IS 'Cadastro de Dependente';


CREATE OR ALTER TRIGGER TGG_PK_DEPENDENTE FOR DEPENDENTE
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  new.id= gen_id(pk_dependente,1);
end